name: Update otrkey files every 30 min

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

permissions:
  contents: write  # Needed for creating/updating releases

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run OTRKey fetch script
        run: python download_otrkey_files.py

      - name: Create or update GitHub release and upload CSV
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: Latest OTRKey Files
          files: otrkey_files.csv
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
