name: Update otrkey files every 15 min

on:
  schedule:
    - cron: '*/15 * * * *' # every 15 minutes
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run OTRKey fetch script
        run: python download_otrkey_files.py

      - name: Commit updated CSV
        uses: EndBug/add-and-commit@v9
        with:
          add: 'otrkey_files.csv'
          message: '⬇️ Update otrkey_files.csv'
          author_name: 'GitHub Actions'
          author_email: 'actions@github.com'
